services:
  nordvpn:
    build: ./nordvpn-client
    container_name: nordvpn-client
    network_mode: "host"
    # Remove privileged if you want to be safe
    # I'm using it because it is my own image
    privileged: true
    #cap_add:
    #  - NET_ADMIN
    #  - NET_RAW
    # Provide access to TUN device
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      # Persist NordVPN data so you don't have to login every time
      - ./data:/var/lib/nordvpn/data
    environment:
      - NORDVPN_TOKEN=${NORDVPN_TOKEN}
      - TECHNOLOGY=${TECHNOLOGY}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - SERVER=${SERVER}
    restart: unless-stopped